name: update-cloudfront-distribution

on:
  push:
    branches:
      - main
    paths:
      - frontend/*
  workflow_dispatch:
 
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REST_API_URL: ${{ secrets.REST_API_URL }}

jobs:
  update:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - name: configure node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: install and build
        working-directory: frontend
        run: |
          npm install
          echo "VITE_API=$REST_API_URL" > .env.production
          npm run build
      - name: upload to s3
        uses: jakejarvis/s3-sync-action@master
        #working-directory: frontend
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET:  ${{ secrets.WEBAPP_BUCKET }}
          AWS_REGION: 'eu-north-1'
          SOURCE_DIR: 'frontend/dist'
