name: update-cloudfront-distribution

on:
  push:
    branches:
      - main
    paths:
      - frontend/*
  workflow_dispatch:
 
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
  AWS_S3_BUCKET:  ${{ secrets.WEBAPP_BUCKET }}
  AWS_REGION: 'eu-north-1'
  SOURCE_DIR: 'frontend/dist'
  REST_API_URL: ${{ secrets.REST_API_URL }}

jobs:
  update-webapp-s3:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - name: configure node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: install and build
        working-directory: frontend
        run: |
          npm install
          echo "VITE_API=$REST_API_URL" > .env.production
          npm run build
      - name: upload to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete

  invalidate-cloudfront: 
    runs-on: "ubuntu-latest"
    needs: update-webapp-s3
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: Koji-Sunioj/trading-grid-cfn
          event-type: updated-cloudfront-app
